// src/constants/permissions.ts

export const ALL_PERMISSIONS = {
  admin_panel: {
    access: 'Access Admin Panel',
  },
  user_management: {
    create: 'Create Users',
    read: 'View Users',
    update: 'Edit Users',
    delete: 'Delete Users',
  },
  role_management: {
    create: 'Create Roles',
    read: 'View Roles',
    update: 'Edit Roles',
    delete: 'Delete Roles',
  },
  hr_employee_details: {
    read: 'View Employee Details (HR)',
    edit: 'Edit Employee Details (HR)',
  },
  sales_module: {
    access: 'Access Sales Module',
    create_invoice: 'Create Sales Invoice',
    read_invoices: 'View Sales Invoices',
    edit_invoices: 'Edit Sales Invoices',
    delete_invoices: 'Delete Sales Invoices',
    create_order: 'Create Sales Order',
    read_orders: 'View Sales Orders',
    edit_orders: 'Edit Sales Orders',
    delete_orders: 'Delete Sales Orders',
    create_quotation: 'Create Sales Quotation',
    read_quotations: 'View Sales Quotations',
    edit_quotations: 'Edit Sales Quotations',
    delete_quotations: 'Delete Sales Quotations',
    create_receipt: 'Create Sales Receipt',
    read_receipts: 'View Sales Receipts',
    edit_receipts: 'Edit Sales Receipts',
    delete_receipts: 'Delete Sales Receipts',
    create_credit_note: 'Create Credit Note',
    read_credit_notes: 'View Credit Notes',
    edit_credit_notes: 'Edit Credit Notes',
    delete_credit_notes: 'Delete Credit Notes',
    create_delivery_challan: 'Create Delivery Challan',
    read_delivery_challans: 'View Delivery Challans',
    edit_delivery_challans: 'Edit Delivery Challans',
    delete_delivery_challan: 'Delete Delivery Challans',
    read_customers: 'View Customers',
    edit_customers: 'Edit Customers',
    read_price_lists: 'View Price Lists',
    edit_price_lists: 'Edit Price Lists',
    sales_analysis: { access: 'Access Sales Analysis' },
    sales_register: { access: 'Access Sales Register' },
    customer_outstanding: { access: 'Access Customer Outstanding' },
    customer_aging_report: { access: 'Access Customer Aging Report' },
  },
  purchase_module: {
    access: 'Access Purchase Module',
    create_po: 'Create Purchase Order',
    read_pos: 'View Purchase Orders',
    edit_pos: 'Edit Purchase Orders',
    delete_pos: 'Delete Purchase Orders',
    create_bill: 'Create Purchase Bill',
    read_bills: 'View Purchase Bills',
    edit_bills: 'Edit Purchase Bills',
    delete_bills: 'Delete Purchase Bills',
    create_grn: 'Create Goods Receipt Note',
    read_grns: 'View Goods Receipt Notes',
    edit_grns: 'Edit Goods Receipt Notes',
    delete_grns: 'Delete Goods Receipt Notes',
    read_vendors: 'View Vendors',
    edit_vendors: 'Edit Vendors',
  },
  accounting_module: {
    access: 'Access Accounting Module',
    create_journal_entry: 'Create Journal Entry',
    read_journal_entries: 'View Journal Entries',
    edit_journal_entries: 'Edit Journal Entries',
    delete_journal_entries: 'Delete Journal Entries',
    read_coa: 'View Chart of Accounts',
    edit_coa: 'Edit Chart of Accounts',
    read_fixed_assets: 'View Fixed Assets',
    edit_fixed_assets: 'Edit Fixed Assets',
    read_reports: 'View Accounting Reports',
  },
  inventory_module: {
    access: 'Access Inventory Module',
    create_item: 'Create Item',
    read_items: 'View Items',
    edit_items: 'Edit Items',
    delete_items: 'Delete Items',
    create_stock_entry: 'Create Stock Entry',
    read_stock_entries: 'View Stock Entries',
    edit_stock_entries: 'Edit Stock Entries',
    delete_stock_entries: 'Delete Stock Entries',
    read_warehouses: 'View Warehouses',
    edit_warehouses: 'Edit Warehouses',
    read_stock_reports: 'View Stock Reports',
  },
  manufacturing_module: {
    access: 'Access Manufacturing Module',
    create_bom: 'Create Bill of Materials',
    read_boms: 'View Bill of Materials',
    edit_boms: 'Edit Bill of Materials',
    delete_boms: 'Delete Bill of Materials',
    create_work_order: 'Create Work Order',
    read_work_orders: 'View Work Orders',
    edit_work_orders: 'Edit Work Orders',
    delete_work_orders: 'Delete Work Orders',
    create_production_entry: 'Create Production Entry',
    read_production_entries: 'View Production Entries',
    edit_production_entries: 'Edit Production Entries',
    delete_production_entries: 'Delete Production Entries',
  },
  reports_module: {
    access: 'Access Reports Module',
    generate_financial_reports: 'Generate Financial Reports',
    generate_sales_reports: 'Generate Sales Reports',
    generate_purchase_reports: 'Generate Purchase Reports',
    generate_inventory_reports: 'Generate Inventory Reports',
  },
  compliance_module: {
    access: 'Access Compliance Module',
    read_tax_returns: 'View Tax Returns',
    file_tax_returns: 'File Tax Returns',
    read_compliance_tasks: 'View Compliance Tasks',
    manage_compliance_tasks: 'Manage Compliance Tasks',
  },
  hr_module: {
    access: 'Access HR Module',
    read_employees: 'View Employees',
    edit_employees: 'Edit Employees',
    read_attendance: 'View Attendance',
    manage_attendance: 'Manage Attendance',
    read_payroll: 'View Payroll',
    manage_payroll: 'Manage Payroll',
    read_leave_applications: 'View Leave Applications',
    manage_leave_applications: 'Manage Leave Applications',
  },
  crm_module: {
    access: 'Access CRM Module',
    read_leads: 'View Leads',
    manage_leads: 'Manage Leads',
    read_opportunities: 'View Opportunities',
    manage_opportunities: 'Manage Opportunities',
    read_campaigns: 'View Campaigns',
    manage_campaigns: 'Manage Campaigns',
    read_activities: 'View Activities',
    manage_activities: 'Manage Activities',
  },
};
