// src/constants/permissions.ts

export const ALL_PERMISSIONS = {
  admin_panel: {
    access: 'Access Admin Panel',
  },
  user_management: {
    create: 'Create Users',
    read: 'View Users',
    update: 'Edit Users',
    delete: 'Delete Users',
  },
  role_management: {
    create: 'Create Roles',
    read: 'View Roles',
    update: 'Edit Roles',
    delete: 'Delete Roles',
  },
  hr_employee_details: {
    read: 'View Employee Details (HR)',
    edit: 'Edit Employee Details (HR)',
  },
  sales_module: {
    access: 'Access Sales Module',
    create_invoice: 'Create Sales Invoice',
    read_invoices: 'View Sales Invoices',
    edit_invoices: 'Edit Sales Invoices',
    delete_invoices: 'Delete Sales Invoices',
    create_order: 'Create Sales Order',
    read_orders: 'View Sales Orders',
    edit_orders: 'Edit Sales Orders',
    delete_orders: 'Delete Sales Orders',
    create_quotation: 'Create Sales Quotation',
    read_quotations: 'View Sales Quotations',
    edit_quotations: 'Edit Sales Quotations',
    delete_quotations: 'Delete Sales Quotations',
    create_receipt: 'Create Sales Receipt',
    read_receipts: 'View Sales Receipts',
    edit_receipts: 'Edit Sales Receipts',
    delete_receipts: 'Delete Sales Receipts',
    create_credit_note: 'Create Credit Note',
    read_credit_notes: 'View Credit Notes',
    edit_credit_notes: 'Edit Credit Notes',
    delete_credit_notes: 'Delete Credit Notes',
    create_delivery_challan: 'Create Delivery Challan',
    read_delivery_challans: 'View Delivery Challans',
    edit_delivery_challans: 'Edit Delivery Challans',
    delete_delivery_challan: 'Delete Delivery Challans',
    read_customers: 'View Customers',
    edit_customers: 'Edit Customers',
    read_price_lists: 'View Price Lists',
    edit_price_lists: 'Edit Price Lists',
    sales_analysis: { access: 'Access Sales Analysis' },
    sales_register: { access: 'Access Sales Register' },
    customer_outstanding: { access: 'Access Customer Outstanding' },
    customer_aging_report: { access: 'Access Customer Aging Report' },
  },
  purchase_module: {
    access: 'Access Purchase Module',
    create_po: 'Create Purchase Order',
    read_pos: 'View Purchase Orders',
    edit_pos: 'Edit Purchase Orders',
    delete_pos: 'Delete Purchase Orders',
    create_bill: 'Create Purchase Bill',
    read_bills: 'View Purchase Bills',
    edit_bills: 'Edit Purchase Bills',
    delete_bills: 'Delete Purchase Bills',
    create_grn: 'Create Goods Receipt Note',
    read_grns: 'View Goods Receipt Notes',
    edit_grns: 'Edit Goods Receipt Notes',
    delete_grns: 'Delete Goods Receipt Notes',
    read_vendors: 'View Vendors',
    edit_vendors: 'Edit Vendors',
  },
  accounting_module: {
    access: 'Access Accounting Module',
    create_journal_entry: 'Create Journal Entry',
    read_journal_entries: 'View Journal Entries',
    edit_journal_entries: 'Edit Journal Entries',
    delete_journal_entries: 'Delete Journal Entries',
    read_coa: 'View Chart of Accounts',
    edit_coa: 'Edit Chart of Accounts',
    read_fixed_assets: 'View Fixed Assets',
    edit_fixed_assets: 'Edit Fixed Assets',
    read_reports: 'View Accounting Reports',
  },
  inventory_module: { // NEW INVENTORY PERMISSIONS
    access: 'Access Inventory Module',
    item_master: {
      create: 'Create Items',
      read: 'View Items',
      update: 'Edit Items',
      delete: 'Delete Items',
    },
    item_categories_groups: {
      create: 'Create Item Categories/Groups',
      read: 'View Item Categories/Groups',
      update: 'Edit Item Categories/Groups',
      delete: 'Delete Item Categories/Groups',
    },
    item_groups: { // NEW: Item Group Permissions
      create: 'Create Item Groups',
      read: 'View Item Groups',
      update: 'Edit Item Groups',
      delete: 'Delete Item Groups',
    },
    units_of_measure: {
      create: 'Create Units of Measure',
      read: 'View Units of Measure',
      update: 'Edit Units of Measure',
      delete: 'Delete Units of Measure',
    },
    warehouses: {
      create: 'Create Warehouses',
      read: 'View Warehouses',
      update: 'Edit Warehouses',
      delete: 'Delete Warehouses',
    },
    stock_transactions: {
      create_adjustment: 'Create Stock Adjustment',
      read_adjustment: 'View Stock Adjustments',
      update_adjustment: 'Edit Stock Adjustments',
      delete_adjustment: 'Delete Stock Adjustments',
      create_transfer: 'Create Stock Transfer',
      read_transfer: 'View Stock Transfers',
      update_transfer: 'Edit Stock Transfers',
      delete_transfer: 'Delete Stock Transfers',
      create_goods_entry: 'Create Goods Receipt/Issue',
      read_goods_entry: 'View Goods Receipts/Issues',
      update_goods_entry: 'Edit Goods Receipts/Issues',
      delete_goods_entry: 'Delete Goods Receipts/Issues',
      read_batch_expiry: 'View Batch/Expiry Data',
      update_batch_expiry: 'Update Batch/Expiry Data',
    },
    inventory_reports: {
      access: 'Access Inventory Reports',
    },
  },
  manufacturing_module: {
    access: 'Access Manufacturing Module',
    create_bom: 'Create Bill of Materials',
    read_boms: 'View Bill of Materials',
    edit_boms: 'Edit Bill of Materials',
    delete_boms: 'Delete Bill of Materials',
    create_work_order: 'Create Work Order',
    read_work_orders: 'View Work Orders',
    edit_work_orders: 'Edit Work Orders',
    delete_work_orders: 'Delete Work Orders',
    create_production_entry: 'Create Production Entry',
    read_production_entries: 'View Production Entries',
    edit_production_entries: 'Edit Production Entries',
    delete_production_entries: 'Delete Production Entries',
  },
  reports_module: {
    access: 'Access Reports Module',
    generate_financial_reports: 'Generate Financial Reports',
    generate_sales_reports: 'Generate Sales Reports',
    generate_purchase_reports: 'Generate Purchase Reports',
    generate_inventory_reports: 'Generate Inventory Reports',
  },
  compliance_module: {
    access: 'Access Compliance Module',
    read_tax_returns: 'View Tax Returns',
    file_tax_returns: 'File Tax Returns',
    read_compliance_tasks: 'View Compliance Tasks',
    manage_compliance_tasks: 'Manage Compliance Tasks',
  },
  hr_module: {
    access: 'Access HR Module',
    read_employees: 'View Employees',
    edit_employees: 'Edit Employees',
    read_attendance: 'View Attendance',
    manage_attendance: 'Manage Attendance',
    read_payroll: 'View Payroll',
    manage_payroll: 'Manage Payroll',
    read_leave_applications: 'View Leave Applications',
    manage_leave_applications: 'Manage Leave Applications',
  },
  crm_module: {
    access: 'Access CRM Module',
    read_leads: 'View Leads',
    create_leads: 'Create Leads',
    update_leads: 'Edit Leads',
    delete_leads: 'Delete Leads',
    convert_leads: 'Convert Leads to Customers',
    read_opportunities: 'View Opportunities',
    create_opportunities: 'Create Opportunities',
    update_opportunities: 'Edit Opportunities',
    delete_opportunities: 'Delete Opportunities',
    read_campaigns: 'View Campaigns',
    create_campaigns: 'Create Campaigns',
    update_campaigns: 'Edit Campaigns',
    delete_campaigns: 'Delete Campaigns',
    read_activities: 'View Activities',
    create_activities: 'Create Activities',
    update_activities: 'Edit Activities',
    delete_activities: 'Delete Activities',
  },
  project_module: { // NEW PROJECT PERMISSIONS
    access: 'Access Project Module',
    read_projects: 'View Projects',
    create_projects: 'Create Projects',
    update_projects: 'Edit Projects',
    delete_projects: 'Delete Projects',
    read_tasks: 'View Tasks',
    create_tasks: 'Create Tasks',
    update_tasks: 'Edit Tasks',
    delete_tasks: 'Delete Tasks',
    log_time: 'Log Time on Tasks',
    read_time_logs: 'View Time Logs',
    project_reports: 'Access Project Reports',
  },
};
